# Generated by Django 3.0.6 on 2020-09-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0002_saving'),
        ('outflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='from_savings',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='loan',
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_savings', models.BooleanField(default=False)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outflow.Debt')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inflow.Loan')),
            ],
        ),
    ]
