# Generated by Django 3.0.6 on 2020-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loss',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
