# Generated by Django 3.0.6 on 2020-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0002_auto_20200910_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
