# Generated by Django 3.0.6 on 2020-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0002_loss_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensein',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
