# Generated by Django 3.0.6 on 2020-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0003_debt_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
