# Generated by Django 3.0.6 on 2020-09-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0003_remove_loan_to'),
        ('outflow', '0004_debt_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inflow.Loan'),
        ),
    ]
