# Generated by Django 3.0.6 on 2020-09-08 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('all_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('liquid_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inflow.CashIn')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cash_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inflow.CashIn')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inflow.CommonFields')),
            ],
            bases=('inflow.commonfields',),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inflow.CommonFields')),
                ('to', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('inflow.commonfields',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inflow.CommonFields')),
            ],
            bases=('inflow.commonfields',),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inflow.CommonFields')),
            ],
            bases=('inflow.commonfields',),
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inflow.Investment')),
            ],
        ),
    ]
