# Generated by Django 3.0.6 on 2020-09-09 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_in', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inflow.CashIn')),
            ],
        ),
    ]
