# Generated by Django 3.0.6 on 2020-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfields',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherin',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
