# Generated by Django 3.0.6 on 2020-09-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0002_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='to',
        ),
    ]
